### ISSUE TITLE
Documentation Metadata

### ISSUE THREAD

**Issue by InteractiveTimmy** [momentum-design/momentum-design#27]
# Request

As a **Contributor and Consumer** of this project, I'd like to have API documentation available in the form of JSON abstracted from inline documentation within the source files.

# Analysis

Implement a flow to convert from inline TSDoc to JSON metadata to be consumed locally. This will likely include using the following packages:

* [eslint-plugin-tsdoc](https://www.npmjs.com/package/eslint-plugin-tsdoc)
  *  Should enforce the requirements for commonly needed tags. May need to also use [eslint-plugin-jsdoc](https://www.npmjs.com/package/eslint-plugin-jsdoc)
* [api-extractor](https://www.npmjs.com/package/@microsoft/api-extractor)
* [api-documenter](https://www.npmjs.com/package/@microsoft/api-documenter)

# Requirements

* [x] Generates consumable JSON articles based on TSDoc within source code
* [x] Produces documentation within the `./docs/metadata` folder for each package

**Comment by torgeadelin** [comment]
#55
